#!/bin/sh
#
# common_functions - some functions used by several scripts
#
# This file is meant to be sourced from $CMROOT/$CI/deploy scripts
# Dependencies: POSIX shell, dirname
#
# $CMROOT
#   |
#   |- lib
#   |   |
#   |   \- common_functions
#   |
#   \- $CI
#       |
#       \- deploy
#
# Possible improvements
#  + Add a specific license
#  + Add tab and newline detection to safety check in init_dirs()
#  + Create tests


if [ $(basename -- "$0") == "common_functions" ]; then
	echo "Don't run this file, source it instead!"
	exit 1
fi


function init_dirs () {
  # See the following page for explanation of CMROOT magic
  # http://stackoverflow.com/questions/8468519/can-a-shell-script-tell-what-directory-its-in-no-bashisms#8506790
  # 2>&1 is there to catch errors spitted by cd in case $0 contains characters from IFS
  CMROOT=$(cd $(dirname -- "$0")/.. 2>&1; pwd)
  if [ "$CMROOT" != "${CMROOT% *}" ]; then
    # Make sure there are no IFS characters in absolute path; needed for copy_bin_files() to work properly
    echo "The path to the current script should not contain any spaces, tabs or newlines"
    exit 1
  fi
  CIROOT="$CMROOT/$CI"
}

